---
# file: roles/java_8/tasks/main.yml
- name: Download Java
  sudo: yes
  command: "wget -q -O {{ java_archive }} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{ download_url }} creates={{ java_archive }}"

- name: Unpack archive
  sudo: yes
  command: "tar -zxf {{ java_archive }} -C {{ download_folder }} creates={{ java_name }}"
 
- name: Fix ownership
  sudo: yes
  file: state=directory path={{ java_name }} owner=root group=root recurse=yes
 
- name: Make Java available for system
  sudo: yes
  command: 'alternatives --install "/usr/bin/java" "java" "{{ java_name }}/bin/java" 2000'
 
- name: Clean up
  sudo: yes
  file: state=absent path={{ java_archive }}