server:
    port: 8443
    ssl:
      key-store: /etc/ssl/keystore-uat.p12
      key-store-password: keystore-uat
      keyStoreType: PKCS12

spring:
    profiles:
        active: uat
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://stlerdbuat.perficient.com:3306/etm
        databaseName: etm
        serverName: stlerdbuat
        username: etmadmin
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    mail:
        baseUrl: https://stlerappuat.perficient.com:8443
        host: mail2.perficient.com
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        from: donotreply@perficient.com

    thymeleaf:
        mode: LEGACYHTML5
        cache: true

    ldap:
        root: dc=perficient,dc=com
        domain: STLCOLODC01.perficient.com
        port: 636
        accountdn: cn=LDAP Enterprise Review,ou=System Accounts,ou=IT

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: etm

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
