server:
    port: 8443
    ssl:
      key-store: /etc/ssl/keystore-dev.p12
      key-store-password: keystore-dev
      keyStoreType: PKCS12

spring:
    profiles:
        active: test
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://stlerdbdev.perficient.com:3306/etm
        databaseName: etm
        serverName: stlerdbdev
        username: etmadmin
        password: K|WH5vum*)3.(fgj7
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            

    mail:
        baseUrl: https://stlerappdev.perficient.com:8443

    thymeleaf:
        mode: LEGACYHTML5
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: etm

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
