<?php

/**
 * @file
 * 
 * This is the counsellor module
 * 
 * 
 */
function counsellor_menu() {
  $items['login'] = array(
    'title' => 'Performance Review Login',
    'page callback' => 'show_login_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'files/performance_review_dashboard.pages.inc',
  );
  $items['newreview'] = array(
    'title' => 'Create Review',
    'page callback' => 'show_pr_list',
    'access arguments' => array('Manage Performance Review List'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'files/performance_review_dashboard.pages.inc',
    'weight' => 5,
  );
  $items['watchpeerreview/%'] = array(
    'title' => 'Watch peer\'s review',
    'type' => MENU_CALLBACK,
    'page callback' => 'watch_peer_review',
    'page arguments' => array(1),
    'access arguments' => array('Manage Performance Review List'),
    'file' => 'files/watch_review.inc',
  );
  $items['newreview/submitreview/%/%'] = array(
    'title' => 'Submit A New Review',
    'type' => MENU_CALLBACK,
    'page callback' => 'submit_new_review',
    'page arguments' => array(2, 3),
    'access arguments' => array('Manage Performance Review List'),
    'file' => 'files/counsellor_create_review.inc',
  );
  $items['newreview/submitselfreview'] = array(
    'title' => 'Submit A New Review',
    'type' => MENU_CALLBACK,
    'page callback' => 'submit_new_self_review',
    'access arguments' => array('Access create self review'),
    'file' => 'files/counsellor_create_review.inc',
  );
  $items['newreview/startreview'] = array(
    'title' => 'Start a review',
    'type' => MENU_CALLBACK,
    'page callback' => 'start_new_review',
    'access arguments' => array('Access create self review'),
    'file' => 'files/counsellor_create_review.inc',
  );
  return $items;
}

function counsellor_block_info() {
//    $blocks['360performance_review_list'] = array(
//        // info: The name of the block.
//        'info' => t('List All Performance Review'),
//        // Block caching options (per role, per user, etc.) 
//        'cache' => DRUPAL_NO_CACHE, // no cache
//    );
  $blocks['basic_info'] = array(
    'info' => t('Basic Info View'),
    'cache' => DRUPAL_NO_CACHE, // no cache
  );
  $blocks['select_participates'] = array(
    'info' => t('Select Participates'),
    'cache' => DRUPAL_NO_CACHE, // no cache
  );
//    $blocks['mail_settings'] = array(
//        'info' => t('Step 3 - Configure mail template'),
//        'cache' => DRUPAL_NO_CACHE, // no cache
//    );

  return $blocks;
}

function counsellor_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
//        case '360performance_review_list':
//            appendCSSJS();
//            $block['subject'] = t('Performance Review Agenda');
//            $block['content'] = pr360_list();
//            break;
    case 'basic_info':
      appendCSSJS();
//            $block['subject'] = render_subject_use_image('Configure Timeslot');
      $nTime = unixTimestampToDateArray('0');
      //information array about my counselor and my anniversary month
      $my_name = get_current_user_name();
      $my_info = get_my_anniversary_counselor($my_name);
      $block['content'] = theme('basic_info_view', array('nTime' => $nTime, 'myInfo' => $my_info));
      break;

    case 'select_participates':
      appendCSSJS();
      $counselees = select_counselees();
      $block['content'] = theme('select_participates', array('counselees' => $counselees));
      break;
//        case 'mail_settings':
////            $block['subject'] = render_subject_use_image('Configure Mail Template');
//            $block['content'] = drupal_get_form('pr360_email_settings_form');
//            break;
  }
  return $block;
}

function counsellor_permission() {
  return array(
    'Manage Performance Review List' => array(
      'title' => t('Access to counsellor create review list'),
    ),
//        'config reviews' => array(
//            'title' => t('Config reviews'),
//        ),
    'Access create self review' => array(
      'title' => t('Access to counsellor or counselee to create self review'),
    ),
  );
}

function appendCSSJS() {
  $counsellor_path = drupal_get_path('module', 'counsellor');
//  drupal_add_css($counsellor_path . '/css/ui.multiselect.css');
//    drupal_add_css($counsellor_path . '/css/ui-lightness/jquery-ui-1.8.16.custom.css');
//    drupal_add_css($counsellor_path . '/css/ui-lightness/colorbox.css');
//    drupal_add_css($counsellor_path . '/reviewlist.css');
//    drupal_add_js($counsellor_path . '/js/jquery.colorbox.js');
//  drupal_add_js($counsellor_path . '/js/ui.multiselect.js');
//  drupal_add_js($counsellor_path . '/js/flatui-radi.js');
  drupal_add_js($counsellor_path . '/js/counsellor.js');
  drupal_add_library('system', 'ui.datepicker');
}

function counsellor_theme() {
  return array(
    'basic_info_view' => array(
      'variables' => array('nTime' => NULL, 'myInfo' => NULL),
      'path' => drupal_get_path('module', 'counsellor') . '/templates',
      'template' => 'basic_info_view',
    ),
    'select_participates' => array(
      'variables' => array('counselees'),
      'path' => drupal_get_path('module', 'counsellor') . '/templates',
      'template' => 'select_participates',
    ),
    'watch_peer_review_basic_info' => array(
      'variables' => array('basic_info'),
      'path' => drupal_get_path('module', 'counsellor') . '/templates',
      'template' => 'watch_peer_review_basic_info',
    ),
    'watch_peer_review_component' => array(
      'variables' => array('component_content'),
      'path' => drupal_get_path('module', 'counsellor') . '/templates',
      'template' => 'watch_peer_review_component',
    ),
    'watch_peer_review_component_select' => array(
      'variables' => array('component_content'),
      'path' => drupal_get_path('module', 'counsellor') . '/templates',
      'template' => 'watch_peer_review_component_select',
    ),
    'watch_peer_review_component_overallrating' => array(
      'variables' => array('component_content'),
      'path' => drupal_get_path('module', 'counsellor') . '/templates',
      'template' => 'watch_peer_review_component_overallrating',
    ),
  );
}

/**
 * get_counselees_from_db
 * @return type
 */
function get_counselees_from_db() {
  $cur_user_name = get_current_user_name();
  $query = db_select('prs_rel_employee_counselor_gm', 'precg');
  $query->fields('precg', array('employeeName'));
  $query->condition('precg.counselorName', $cur_user_name, '=');
  $query->orderBy('precg.employeeName', 'ASC');
  $result = $query->execute()->fetchAll();

  return $result;
}

/**
 * get_counselees_from_db with user name
 * @return type
 */
function get_counselees_from_db_with_username($cur_user_name) {
  $query = db_select('prs_rel_employee_counselor_gm', 'precg');
  $query->fields('precg', array('employeeName'));
  $query->condition('precg.counselorName', $cur_user_name, '=');
  $query->orderBy('precg.employeeName', 'ASC');
  $results = $query->execute()->fetchAll();
  $result = array();
  foreach ($results as $one_result) {
    array_push($result, $one_result->employeeName);
  }
  return $result;
}

/**
 * generate_selected_participant_array
 * @param type $counseleeNames
 * @return array
 */
function generate_selected_participant_array($counseleeNames) {
  $counselee_names_array = array();
  foreach ($counseleeNames as $key => $selectName) {
    $employee_name = $selectName->employeeName;
    array_push($counselee_names_array, $employee_name);
  }
  return $counselee_names_array;
}

/**
 * select_counselees
 * @return array
 */
function select_counselees() {
  $counselee_names = get_counselees_from_db();
  return generate_selected_participant_array($counselee_names);
}