<?php

/**
 * @file 
 * custom webform field here
 */

/**
 * implement hook_webform_component_info()
 * @return type 
 */
function custom_webform_field_webform_component_info() {
  return array(
    'lastyeargoal' => array(
      'label' => t('Last Year Goals'),
      'description' => t('show counselee\'s last year goal.'),
      'features' => array(
        'csv' => FALSE,
        'required' => FALSE,
        'conditional' => FALSE,
        'group' => TRUE,
        'title_display' => FALSE,
      ),
      'file' => 'components/lastyeargoal.inc',
    ),
    'compositescore' => array(
      'label' => t('Composite Score'),
      'description' => t('Display the the score calculate result'),
      'features' => array(
        'csv' => FALSE,
        'default_value' => FALSE,
        'required' => FALSE,
        'conditional' => FALSE,
        'title_display' => FALSE,
      ),
      'file' => 'components/compositescore.inc',
    ),
    'basicinformation' => array(
      'label' => t('Basic Information'),
      'description' => t('Display the peer review form basic information'),
      'features' => array(
        'csv' => FALSE,
        'default_value' => FALSE,
        'required' => FALSE,
        'conditional' => FALSE,
        'title_display' => FALSE,
      ),
      'file' => 'components/basicinformation.inc',
    ),
    'overallscore' => array(
      'label' => t('Overall Composite Scores'),
      'description' => t('Display the peer review form basic information'),
      'features' => array(
        'csv' => FALSE,
        'default_value' => FALSE,
        'required' => FALSE,
        'conditional' => FALSE,
        'title_display' => FALSE,
      ),
      'file' => 'components/overallscore.inc',
    ),
    'projectroles' => array(
      'label' => t('Project Roles'),
      'description' => t('Display the project roles message'),
      'features' => array(
        'csv' => FALSE,
        'default_value' => FALSE,
        'required' => FALSE,
        'conditional' => FALSE,
        'title_display' => FALSE,
      ),
      'file' => 'components/projectroles.inc',
    ),
  );
}

/**
 * Implement hook_theme
 * 
 */
function custom_webform_field_theme() {
  return array(
    'peer-review-form' => array(
      'variables' => array('basic_info' => null),
      'path' => drupal_get_path('module', 'custom_webform_field') . '/templates',
      'template' => 'peer-review-form-basic-information',),
    'peer-review-form-overall' => array(
      'variables' => array('score_overall' => null, 'table_head' => null),
      'path' => drupal_get_path('module', 'custom_webform_field') . '/templates',
      'template' => 'peer-review-form-overall',),
    'project-roles-and-responsebilities' => array(
      'variables' => array(
        'projects' => null,
        'nid' => NULL,
      ),
      'path' => drupal_get_path('module', 'custom_webform_field') . '/templates',
      'template' => 'project-roles-and-responsebilities'),
  );
}

function custom_webform_field_menu() {
  $items['annual/save-project-roles'] = array(
    'title' => 'Save Project Roles',
    'page callback' => 'save_project_roles',
    'page arguments' => array(),
    'access arguments' => array('access to my dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'components/projectroles.inc',);

  return $items;
}
